DELETE FROM DB_CEIBA_RENTA_PELICULA.CLIENTE;
DELETE FROM DB_CEIBA_RENTA_PELICULA.PELUCULA;
DELETE FROM DB_CEIBA_RENTA_PELICULA.PRESTAMO;

INSERT INTO DB_CEIBA_RENTA_PELICULA.CLIENTE VALUE ( 123, "gabriel", "arboleda" );
INSERT INTO DB_CEIBA_RENTA_PELICULA.CLIENTE VALUE ( 321, "andres", "tolosa" );